### ISSUE TITLE
imdb flipping image boxes has a typo?

### ISSUE THREAD

**Issue by Ahmed-M-Naguib** [CharlesShang/TFFRCNN#113]
Hi,
i'm trying to train the net on my own data and classes.

i'm getting assertion error in imdb.py line 120

the lines are:

boxes = self.roidb[i]['boxes'].copy()
oldx1 = boxes[:, 0].copy()
oldx2 = boxes[:, 2].copy()
boxes[:, 0] = widths[i] - oldx2 - 1
boxes[:, 2] = widths[i] - oldx1 - 1
assert (boxes[:, 2] >= boxes[:, 0]).all()

i'm not sure. if the purpose is to flip image boxes, shouldn't it be like:
boxes[:, 0] = widths[i] - oldx1 - 1
boxes[:, 2] = widths[i] - oldx2 - 1

since boxes[0] is x1, and boxes[2] is x2?

UPDATE:
sorry, i just though about it.
nevermind!

**Comment by pale1018** [comment]
I have the same question, could you please tell me how to fix it ?
