### ISSUE TITLE
AssertionError: Single batch only

### ISSUE THREAD

**Issue by zilunzhang** [CharlesShang/TFFRCNN#115]
I am sorry but I really cannot solve this problem...

I had this message when I try to run train_net using KITTI data set.

Error message is:

Traceback (most recent call last):
...
line 39, in get_minibatch
    assert len(im_scales) == 1, "Single batch only"
AssertionError: Single batch only

Any idea why this happen...? We only can pass one batch at a time? How to deal with that on KITTI train set...?

Thank you!

**Comment by XChuanLee** [comment]
hello I have the same problem. Have you solved it already? Help...

**Comment by zilunzhang** [comment]
Yep, change the batch number to 1 in lib/fast_rcnn/configuration

**Comment by wuhaotju** [comment]
can you more detail? i also meet the problem,but i train use the first data set.

**Comment by chiyandetaotie** [comment]
@zilunzhang can you more detail? i also meet the problem,but i train use the first data set.

**Comment by zilunzhang** [comment]
Sure, just click lib/fast_rcnn/configuration file and change batch number option to 1, then you should be fine.

**Comment by zilunzhang** [comment]
@chiyandetaotie @wuhaotju 

Sure, just click lib/fast_rcnn/configuration file and change batch number option to 1, then you should be fine.
