### ISSUE TITLE
Question about the mAP of VGG?

### ISSUE THREAD

**Issue by jinhou** [CharlesShang/TFFRCNN#12]
Hi, 
I saw your trained model of VGGnet with two different mAP numbers as below,
VGG16 - TFFRCNN (0.689 mAP on VOC07)
VGG16 - TFFRCNN (0.748 mAP on VOC07)

The first one is align with the numbers reported in the original paper. The second one is much higher than the original paper. I am wondered what you had changed for this version? Thanks

**Comment by CharlesShang** [comment]
Just adding VOC12 trainval set
