### ISSUE TITLE
'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by Esugi8** [CharlesShang/TFFRCNN#16]
When I tried to run training scripts written on "README.md", I got an Error message below.
Could you please let me know how to solve this issue?

python ./faster_rcnn/train_net.py --gpu 0 --weights ./data/pretrain_model/VGG_imagenet.npy --imdb voc_2007_trainval --iters 70000 --cfg  ./experiments/cfgs/faster_rcnn_end2end.yml --network VGGnet_train --set EXP_DIR exp_dir
　　　　　　　　　　　　　　　　　　　　⇩⇩⇩

Solving...
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients.py:90: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 396, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 167, in train_model
    raise 'Check your pretrained {:s}'.format(ckpt.model_checkpoint_path)
**AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'**

My developing environment is below
Tensorflow：0.11.0
GPU/CPU：GPU
Python:2.7.6

**Comment by civilman628** [comment]
add training parameter  --restore 0 

be default, it tries to start from a previous check point, as you train from start, there is no check point yet.

**Comment by civilman628** [comment]
--set EXP_DIR exp_dir is not necessary

**Comment by Esugi8** [comment]
The issue has been solved.
Thank you so much for your advice!!

**Comment by HaoWangDL** [comment]
@Esugi8 Hello，
I also met this problem. How do you solve it
