### ISSUE TITLE
code error: file not found if you do not update line113 in demo.py

### ISSUE THREAD

**Issue by civilman628** [CharlesShang/TFFRCNN#17]
https://github.com/CharlesShang/TFFRCNN/blob/master/faster_rcnn/demo.py#L113

this line should change to **if args.model == ' ' :**    

else if you train your own model and set **--model '/your/model/file.ckpt'** will fail. since the output of train for each snapshot is not .ckpt, but 3 files.

**Comment by CharlesShang** [comment]
Thank you for your suggestions. 
I have not maintained demo.py for quite a long time.
