### ISSUE TITLE
 error when running the demo

### ISSUE THREAD

**Issue by xinghedyc** [CharlesShang/TFFRCNN#2]
Hi, I meet error when running the demo.
Traceback (most recent call last):
  File "faster_rcnn/demo.py", line 12, in <module>
    from lib.networks.factory import get_network
  File "/home/dyc/workspace/TFFRCNN/lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "/home/dyc/workspace/TFFRCNN/lib/networks/VGGnet_train.py", line 2, in <module>
    from network import Network
  File "/home/dyc/workspace/TFFRCNN/lib/networks/network.py", line 4, in <module>
    from ..roi_pooling_layer import roi_pooling_op as roi_pool_op
  File "/home/dyc/workspace/TFFRCNN/lib/roi_pooling_layer/__init__.py", line 7, in <module>
    import roi_pooling_op
  File "/home/dyc/workspace/TFFRCNN/lib/roi_pooling_layer/roi_pooling_op.py", line 5, in <module>
    _roi_pooling_module = tf.load_op_library(filename)
  File "/home/dyc/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 63, in load_op_library
    raise errors._make_specific_exception(None, None, error_msg, error_code)
tensorflow.python.framework.errors.NotFoundError: /home/dyc/workspace/TFFRCNN/lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE

**Comment by CharlesShang** [comment]
Hi, @xinghedyc , I think you first should go to ./lib/ dir and run `make`

**Comment by CharlesShang** [comment]
Maybe, you should edit the g++ config according to your platform to ensure the roi_pooing.so is correct. 
See `./lib/make.sh`

**Comment by xinghedyc** [comment]
@CharlesShang thanks for your reply, but the make command seems right to generate roi_pooing.so.

**Comment by xinghedyc** [comment]
@CharlesShang thanks for your reply, but the make command seems right to generate roi_pooing.so.

**Comment by CharlesShang** [comment]
It happened to me too, the roi_pooing.so seems all right, but it just could not work. 
Check this issue: [Failed when running tf.load_op_library(roi_pooling_so) ](https://github.com/smallcorgi/Faster-RCNN_TF/issues/7
)
It's very embarrassing to say that I've not figured out the real solution. Alternatively, you can download a already-compiled .so file, or try re-start your machine.

**Comment by xinghedyc** [comment]
@CharlesShang thanks a lot, but your link to download the roi_pooling_so seems unreachable?
https://github.com/CharlesShang/TFFRCNN/tree/master/lib/roi_pooling_layer/roi_pooling.so
it shows 404 not found?

**Comment by CharlesShang** [comment]
Try this link [so version](https://github.com/CharlesShang/TFFRCNN/tree/roi_pooling/lib/roi_pooling_layer)

**Comment by xinghedyc** [comment]
@CharlesShang it's embarrassingto say that the same error occurs when using your .so file.
It's so strange.
Thanks you anyway!

**Comment by xinghedyc** [comment]
python faster_rcnn/demo.py VGGnet_fast_rcnn_iter_70000.ckpt 
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so locally
faster_rcnn
Traceback (most recent call last):
  File "faster_rcnn/demo.py", line 12, in <module>
    from lib.networks.factory import get_network
  File "/home/dyc/workspace/TFFRCNN/lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "/home/dyc/workspace/TFFRCNN/lib/networks/VGGnet_train.py", line 2, in <module>
    from network import Network
  File "/home/dyc/workspace/TFFRCNN/lib/networks/network.py", line 4, in <module>
    from ..roi_pooling_layer import roi_pooling_op as roi_pool_op
  File "/home/dyc/workspace/TFFRCNN/lib/roi_pooling_layer/__init__.py", line 7, in <module>
    import roi_pooling_op
  File "/home/dyc/workspace/TFFRCNN/lib/roi_pooling_layer/roi_pooling_op.py", line 5, in <module>
    _roi_pooling_module = tf.load_op_library(filename)
  File "/home/dyc/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 63, in load_op_library
    raise errors._make_specific_exception(None, None, error_msg, error_code)
tensorflow.python.framework.errors.NotFoundError: /home/dyc/workspace/TFFRCNN/lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE

**Comment by CharlesShang** [comment]
I googled it, found: https://github.com/GPflow/GPflow/issues/173
According to james, the problem is tf and roi_pooling are built with different versions of g++,
Try to add  `-D_GLIBCXX_USE_CXX11_ABI=0` in your make.sh will solve this issue

I've already push the fixed make.sh to master branch, you can go to TFFRCNN root dir and run `git pull`, then complie the roi_pooling.so

**Comment by CharlesShang** [comment]
If it does not work, try to install a different version of g++, via `sudo apt-get install g++-4.x` or `sudo apt-get install g++-5.x`
Then run 
`sudo rm  /usr/bin/g++`
`sudo ln -s /usr/bin/g++-4.x /usr/bin/g++`

**Comment by xinghedyc** [comment]
@CharlesShang thanks very much for your help!
it works now, really thanks you!

**Comment by CharlesShang** [comment]
Glad to hear that. Maybe we've found out the real solution to this kind of issue

**Comment by jwnsu** [comment]
for gcc5, simply add this to compile flag "-D_GLIBCXX_USE_CXX11_ABI=0", then it will work fine. It's documented issue by tensor flow: https://www.tensorflow.org/versions/r0.10/how_tos/adding_an_op/index.html

**Comment by CharlesShang** [comment]
@jwnsu Thanks for your helpful discussion. Learned a lot .

**Comment by civilman628** [comment]
update as:

	g++ -std=c++11 -shared -o roi_pooling.so roi_pooling_op.cc  -D_GLIBCXX_USE_CXX11_ABI=0  \
		roi_pooling_op.cu.o -I $TF_INC  -D GOOGLE_CUDA=1 -fPIC $CXXFLAGS \
		-lcudart -L $CUDA_PATH/lib64

**Comment by eragonruan** [comment]
I got an error when running the demo.
AttributeError: 'module' object has no attribute 'RegisterShape'
I googled it ,but found nothing useful, is there something wrong with my environment?Thanks a lot

**Comment by nsivaramakrishnan** [comment]
Hi,
   I am getting the same error while trying to run demo.py:
tensorflow.python.framework.errors_impl.NotFoundError: /home/fmc/rcnn/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _Z22ROIPoolBackwardLaucherPKffiiiiiiiS0_PfPKiRKN5Eigen9GpuDeviceE
I added "-D_GLIBCXX_USE_CXX11_ABI=0" in make,sh. I use g++ version 5.4.0 and TF V0.12. Btw, am trying to run this on CPU. Any help is highly appreciated.
-Siva

**Comment by chaochaow** [comment]
@nsivaramakrishnan I got the same problem like yours when running on CPU. Do you have any luck to solve this issue?

**Comment by louisquinn** [comment]
@nsivaramakrishnan @chaochaow 
I'm getting a similar issue when attempting to build for CPU:
Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

This looks like a missing tensorflow symbol. 
I'm using g++ v5.4.0 as well. Not sure if downgrading to v4.x will help.

**Comment by chaochaow** [comment]
GPU version does not have this problem

**Comment by kalanityL** [comment]
I had the issue with GPU
solution given by @Griovwe [here](https://github.com/CharlesShang/TFFRCNN/issues/55#) worked:
you have to add "-D_GLIBCXX_USE_CXX11_ABI=0" to both the g++ lines for roi_pooling layer and psroi_pooling layer if you encountered this problem.
