### ISSUE TITLE
Assert error : invalid boxes found 

### ISSUE THREAD

**Issue by eragonruan** [CharlesShang/TFFRCNN#23]
I try to train the net on my own dataset. And I got this error in /lib/fast_rcnn/bbox_transform.

image: COCO_train2014_000000120718.jpg
Traceback (most recent call last):
  File "/home/slade/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 85, in __call__
    ret = func(*args)
  File "./faster_rcnn/../lib/rpn_msr/proposal_target_layer_tf.py", line 78, in proposal_target_layer
    rois_per_image, _num_classes)
  File "./faster_rcnn/../lib/rpn_msr/proposal_target_layer_tf.py", line 182, in _sample_rois
    rois[:, 1:5], gt_boxes[gt_assignment[keep_inds], :4], labels)
  File "./faster_rcnn/../lib/rpn_msr/proposal_target_layer_tf.py", line 224, in _compute_targets
    targets = bbox_transform(ex_rois, gt_rois)
  File "./faster_rcnn/../lib/fast_rcnn/bbox_transform.py", line 25, in bbox_transform
    format(ex_rois[np.argmin(ex_widths), :], ex_rois[np.argmin(ex_heights), :])
AssertionError: Invalid boxes found: [ 81557.203125      205.16482544   -285.29534912    257.66482544] [   1.25  280.     95.    297.5 ]

I compared your work with smallcorgi. Found that you added the assertion in the code.
Any idea why this error occurred？I tried to change the RNG_SEED in config.py, also tried to lower 
learning rate. but this error still exist. Looking forward to your answers. Thanks a lot.

**Comment by CharlesShang** [comment]
Thank you for your feedback.
In practice, I always encountered `np.exp(dw)` overflow warnings in `bbox_transform_inv` the reason of which was `rpn_bbox_pred` were too large ( like exp(200) ). Then the network would converge to 'nan'. 
This assertion is to help me locate invalid boxes, but I think I should add  `np.min(ex_widths) < MAX_SIZE`

The best practice to preventing invalid boxes is to lower down the stddev (from 0.01 to 0.001) when initialize the `rpn_bbox_pred` layer

**Comment by eragonruan** [comment]
Thanks a lot. It works well when lower down the stddev.

**Comment by JisuiWang** [comment]
Tensorflow is new to me and I don't know how to lower down the stddev when initializing the rpn_bbox_pred layer. Can you tell me more details about it? Thanks. @eragonruan  @CharlesShang

**Comment by juzhitao** [comment]
how to modify code to down stddev?

**Comment by amirmgh1375** [comment]
its just for dataset annotations.
you should modify the `pascal_voc.py` code as follows :+1: 

`x1 = max(float(bbox.find('xmin').text), 0)`
`y1 = max(float(bbox.find('ymin').text) , 0)`
`x2 = max(float(bbox.find('xmax').text) , 0)`
`y2 = max(float(bbox.find('ymax').text) , 0)`
or  
`x1 = max(float(bbox.find('xmin').text) - 1, 0)`
`y1 = max(float(bbox.find('ymin').text) - 1, 0)`
`x2 = max(float(bbox.find('xmax').text)  - 1, 0)`
`y2 = max(float(bbox.find('ymax').text)  - 1, 0)`
