### ISSUE TITLE
change from tf.image_summary to tf.summary.image

### ISSUE THREAD

**Issue by chefwen** [CharlesShang/TFFRCNN#25]
I am using tensorflow 0.12, after change` log_image = tf.image_summary(log_image_name, tf.expand_dims(log_image_data, 0), max_images=1)` to `log_image = tf.summary.image(log_image_name, tf.expand_dims(log_image_data, 0), max_outputs=1)`

Got the error:

>   File "./faster_rcnn/../lib/fast_rcnn/train.py", line 97, in build_image_summary
>     log_image = tf.summary.image(log_image_name, tf.expand_dims(log_image_data, 0), max_outputs=1)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/summary.py", line 168, in image
>     name = _clean_tag(name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/summary.py", line 88, in _clean_tag
>     new_name = _INVALID_TAG_CHARACTERS.sub('_', name)
> TypeError: expected string or buffer

Thanks!

**Comment by CharlesShang** [comment]
Now the lastest TF version this codebase supports is 0.11. 
TF 0.12 changes some APIs. Plz use `tf_update.py` to update the codebase. 
A temporary solution to this problem: 
```
log_image_data = tf.placeholder(tf.uint8, [None, None, 3])
log_image_name = tf.placeholder(tf.string)
from tensorflow.python.ops import gen_logging_ops
from tensorflow.python.framework import ops as _ops
log_image = gen_logging_ops._image_summary(log_image_name, tf.expand_dims(log_image_data, 0), max_images=1)
_ops.add_to_collection(_ops.GraphKeys.SUMMARIES, log_image)
```
https://github.com/tensorflow/tensorflow/issues/7964
https://github.com/tensorflow/tensorflow/pull/5558

**Comment by tsstjj** [comment]
> I am using tensorflow 0.11, and I used   log_image = tf.summary.image(log_image_name, tf.expand_dims(log_image_data, 0), max_outputs=1)`

> Got the error:
Traceback (most recent call last):
  File "/home/xiongxiong/TFFRCNN/faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "/home/xiongxiong/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 402, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "/home/xiongxiong/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 127, in train_model
    self.build_image_summary()
  File "/home/xiongxiong/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 102, in build_image_summary
    log_image = tf.summary.image(log_image_name, tf.expand_dims(log_image_data, 0), max_outputs=1)
  File "/home/xiongxiong/anaconda3/lib/python3.5/site-packages/tensorflow/python/summary/summary.py", line 144, in image
    name, family, values=[tensor]) as (tag, scope):
  File "/home/xiongxiong/anaconda3/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/xiongxiong/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/summary_op_util.py", line 104, in summary_scope
    name = clean_tag(name)
  File "/home/xiongxiong/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/summary_op_util.py", line 73, in clean_tag
    new_name = _INVALID_TAG_CHARACTERS.sub('_', name)
TypeError: expected string or bytes-like object


Thanks!

**Comment by tjzjp** [comment]
> I am using tensorflow 0.11, and I used   log_image = tf.summary.image(log_image_name, tf.expand_dims(log_image_data, 0), max_outputs=1)`
> 
> 
> Got the error:
> Traceback (most recent call last):
> File "/home/xiongxiong/TFFRCNN/faster_rcnn/train_net.py", line 109, in 
> restore=bool(int(args.restore)))
> File "/home/xiongxiong/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 402, in train_net
> sw.train_model(sess, max_iters, restore=restore)
> File "/home/xiongxiong/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 127, in train_model
> self.build_image_summary()
> File "/home/xiongxiong/TFFRCNN/faster_rcnn/../lib/fast_rcnn/train.py", line 102, in build_image_summary
> log_image = tf.summary.image(log_image_name, tf.expand_dims(log_image_data, 0), max_outputs=1)
> File "/home/xiongxiong/anaconda3/lib/python3.5/site-packages/tensorflow/python/summary/summary.py", line 144, in image
> name, family, values=[tensor]) as (tag, scope):
> File "/home/xiongxiong/anaconda3/lib/python3.5/contextlib.py", line 59, in enter
> return next(self.gen)
> File "/home/xiongxiong/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/summary_op_util.py", line 104, in summary_scope
> name = clean_tag(name)
> File "/home/xiongxiong/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/summary_op_util.py", line 73, in clean_tag
> new_name = INVALID_TAG_CHARACTERS.sub('', name)
> TypeError: expected string or bytes-like object
> 
> Thanks!

I met the same problem as yours, have you fix it?
