### ISSUE TITLE
Very nice new features.. and any mAP improvement?

### ISSUE THREAD

**Issue by jwnsu** [CharlesShang/TFFRCNN#26]
Notice very nice new changes (TF1, hard example mining, data augmentation, and Planet). Wondering whether they improve mAP numbers.

Thanks!!!

**Comment by CharlesShang** [comment]
Haven't tested it yet.

**Comment by jwnsu** [comment]
Tried new version on a different dataset (not Pascal VOC), it's about 0.95% lower in mAP.

**Comment by CharlesShang** [comment]
I got the same conclusion. 
I'm wonder how they perform hard sample mining...

**Comment by jwnsu** [comment]
At 40K iterations, OHEM actually outperforms original training by 1.5% percentage point (outperforms about 0.8% at 30K iterations.) Then it starts to underperform afterward. 

The original OEHM paper (arxiv 1604.03540v1) states:"We train all methods with SGD for 80k mini- batch iterations, with an initial learning rate of 0.001 and we decay the learning rate by 0.1 every 30k iterations."

Maybe reduce learning rate after certain # of iterations? Current training stays at 0.0001 constant learning rate. Another idea is increase initial lr to 0.001 and then reduces.

Elsewhere, for SSD model, Wei reported he was not able to see any benefit from OHEM.
