### ISSUE TITLE
pva test error

### ISSUE THREAD

**Issue by jwnsu** [CharlesShang/TFFRCNN#27]
pva training works fine, but reports following test error:
"InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,768,384] rhs shape= [1,1,384,384]
	 [[Node: save/Assign_481 = Assign[T=DT_FLOAT, _class=["loc:@convf_2/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](convf_2/weights, save/RestoreV2_481/_35)]]"

Probably mismatch somewhere between PVAnet_train/test.

ps: faster_rcnn/test_net.py needs to change line 70 (added args.model + '.index')

**Comment by jwnsu** [comment]
the test error is fixed by modifying _test network definition. However, current version of PVAnet does not seem to produce meaningful result.

**Comment by umangsa** [comment]
HI jwnsu, what did you change in the code? I am facing the same issue
