### ISSUE TITLE
the mAP compared to py-faster-rcnn

### ISSUE THREAD

**Issue by xinghedyc** [CharlesShang/TFFRCNN#3]
sorry to bother you again.
I find it your checkpoint given is about 65% mAP on pascal 2007 test set.
does it need more iters to train?
I also train for about 70k iters but can only reach 50% mAP.

**Comment by CharlesShang** [comment]
I noticed that, too. And I'm working on this problem.
Some code (VGGnet_fast_rcnn_iter_70000.ckpt) was based on caffe model, in the shape of 1xCxHxW, so it needed a lot transpose and reshape before and after anchor layer and rpn layer.  While I tried to simplify this process, I did some modification in these layers. That explains why there is a drop in mAP with the provided model. 

I also found out the parameters, like BBOX_INSIDE_WEIGHTS, BBOX_NORMALIZE_STDS, matered a lot, which I tried to get rid of them, because I thought it's too complex for understanding.
I'll reconsider to add the paramters. 
Thank you for your important feedback!

**Comment by CharlesShang** [comment]
@xinghedyc 
I did a small modification in proposal_layer_tf.py. 
Now we can evaluate the [old model](https://drive.google.com/open?id=0ByuDEGFYmWsbZ0EzeUlHcGFIVWM) via: 
- uncomment `scores = rpn_cls_prob_reshape[:,:,:,_num_anchors:]` in proposal_layer_tf.py
- run  `./experiments/eval/voc2007_test.sh`

I got the same results:
AP for aeroplane = 0.6980
AP for bicycle = 0.7883
AP for bird = 0.6566
AP for boat = 0.5602
AP for bottle = 0.4778
AP for bus = 0.7620
AP for car = 0.7971
AP for cat = 0.7927
AP for chair = 0.4781
AP for cow = 0.7243
AP for diningtable = 0.6478
AP for dog = 0.8020
AP for horse = 0.7968
AP for motorbike = 0.7319
AP for person = 0.7706
AP for pottedplant = 0.3827
AP for sheep = 0.6642
AP for sofa = 0.6503
AP for train = 0.7660
AP for tvmonitor = 0.6669
Mean AP = 0.6807

**Comment by xinghedyc** [comment]
@CharlesShang thanks a lot!
I'll try it, and if I wanna train the model from the start, should I take 70k iters which 50k for learning rate of 0.001 and the rest 20k iters for learning rate of 0.0001?
I find your config file that learning rate is divided by 10 every 30k iters.

**Comment by CharlesShang** [comment]
This is from the original paper.

> We use a learning rate of 0.001
for 60k mini-batches, and 0.0001 for the next 20k
mini-batches on the PASCAL VOC dataset. We use a
momentum of 0.9 and a weight decay of 0.0005

**Comment by xinghedyc** [comment]
@CharlesShang Hi, I read your readme about kitti converting to pascal format. 
Does kitti test set has labels?
And how much memory does it cost when training on kitti, I'm using gtx1080 and get a out of memory abort in the trainning time.
Thanks.

**Comment by CharlesShang** [comment]
KITTI does not provide testing labels.
GTX1080' RAM is enough for training 2xkitti (about 700x2400).
There's a recent paper, A Unified Multi-scale Deep Convolutional Neural Network for Fast Object Detection, disscussing the parameter setting for kitti. Scaling the input image by 1.5~2 will results about 3 percents gain in mAP.

**Comment by xinghedyc** [comment]
thanks a lot for your information！

**Comment by CharlesShang** [comment]
So far, I got the mAP 0.65 after 70k iters training, still toooooo low for us.
I did a little modification in the loss layer, I'll retrain on voc07 for 70iters with the exactly same paramesters.

**Comment by xinghedyc** [comment]
@CharlesShang If I want evaluate the checkpoint trained myself on pascal and kitti, Do I need to uncomment the line scores = rpn_cls_prob_reshape[:,:,:,_num_anchors:] in proposal_layer_tf.py?

**Comment by CharlesShang** [comment]
> If I want evaluate the checkpoint trained myself on pascal and kitti, Do I need to uncomment the line scores = rpn_cls_prob_reshape[:,:,:,_num_anchors:] in proposal_layer_tf.py?

The answer is yes. 
```python
    # TODO: NOTICE: the old version is ordered by (1, H, W, 2, A) !!!!
    # TODO: if you use the old trained model, VGGnet_fast_rcnn_iter_70000.ckpt, uncomment this line
    scores = rpn_cls_prob_reshape[:,:,:,_num_anchors:]
```

**Comment by CharlesShang** [comment]
Plz notice the order is different. 
In the old implementation, the rpn_label is ordered by (H, W, 2, A), A is the number of anchors. 
To be more elegant,  I change that to (H, W, A, 2), just like the rpn_boxes.

**Comment by CharlesShang** [comment]
So far, the best mAP I got after 80k iters is 0.685 (0.699 in the original paper). 

There're still improvement, like tuning loss_weight, adding regularization (there is no regularization in the current version).  
Now I'm closing this issue. 
I'll solve it in a few days.

**Comment by Fansiee** [comment]
I met the same problem. I train the resnet50 70000iters, but the result is just 0.29, and after uncomment the line, the result is 0.128...

**Comment by 1992039674** [comment]
How can I get the value of mAP?

**Comment by 1992039674** [comment]
How can I get the value of AP? Please tell me,   please ,please~
