### ISSUE TITLE
Running demo on CPU

### ISSUE THREAD

**Issue by SeanTyco** [CharlesShang/TFFRCNN#30]
Is it possible to run the demo script on a machine without a gpu? As in, without CUDA or CUDNN?

**Comment by jwnsu** [comment]
It runs well on CPU, need to change configure.py to change NMS to CPU only.

**Comment by SeanTyco** [comment]
I cannot make the libraries without CUDA. I'm trying to run it in a docker container that doesn't have CUDA or CUDNN installed.

**Comment by CharlesShang** [comment]
I have no ideas, I never used cpu to run this code. 
But it's possible, just need to re-complie  `roi_pooling.so` and `nms` without gpu support.

**Comment by sevaxyz** [comment]
@SeanTyco @CharlesShang Do I understand correctly there is no straightforward way to compile them for CPU without supplementing the code?

In `roi_pooling_op.cc`, there is a function `ROIPoolBackwardLaucher` that is defined only in `roi_pooling_op_gpu.cu.cc` and is written to be using `ROIPoolBackward` CUDA kernel. I cannot find the CPU counterpart.
