### ISSUE TITLE
An error when training on VOC

### ISSUE THREAD

**Issue by wmmxk** [CharlesShang/TFFRCNN#31]
Hi Charles,
Thanks for sharing your code. After run the demo successfully, I run the command for training the faster-rccn on VOC and run into this error:
 File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 400, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 171, in train_model
    raise 'Check your pretrained {:s}'.format(ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'
Do you have any ideas how to fix it?

Thanks.

**Comment by CharlesShang** [comment]
A guess is TF1.0 has change this `model_checkpoint_path` attribute in `ckpt`. 
I'm a little busy right now. Have you done some checks? 
plz keep me informed

**Comment by CharlesShang** [comment]
TF1.0, restore checkpoint: 
```
restorer = tf.train.Saver() # restoring all the vars
restorer.restore(sess, tf.train.latest_checkpoint(checkpoint_dir))
```

**Comment by ruyiwei-cas** [comment]
so ,how do i solve this problem @CharlesShang?

**Comment by ruyiwei-cas** [comment]
thx ,i fix this problem exchange comman as :
sudo python ./faster_rcnn/train_net.py --gpu 0 --weight ./data/pretrain_model/VGG_imagenet.npy --imdb voc_2007_trainval --iters 70000 --cfg ./experiments/cfgs/faster_rcnn_end2end.yml **--restore 0**  --network VGGnet_train --set EXP_DIR exp.
