### ISSUE TITLE
training speed problem

### ISSUE THREAD

**Issue by xinghedyc** [CharlesShang/TFFRCNN#4]
Hi , I find a strange problem that my training speed seems to go down,
it says 0 to 10k iters cost 50minites 10k to 20k costs 2 hours and 20k to 30k cost even more time.
But the log says the speed per iter is always the same like 0.2s/iter.
so I dont know why this happens.

**Comment by xinghedyc** [comment]
I see this
if iter >= cfg.TRAIN.STEPSIZE:
                sess.run(tf.assign(lr, cfg.TRAIN.LEARNING_RATE * cfg.TRAIN.GAMMA))
            else:
                sess.run(tf.assign(lr, cfg.TRAIN.LEARNING_RATE))
this op execute every iter, I try to move it outside the loop, it seems speed up the training.

**Comment by CharlesShang** [comment]
I have the same problem with you, my GPU is GTX 980, runs pretty fast at the beginning, but gets worse after saveral epoches.
I tried to profile the process to check how much the loading data module costed, (see `./experiments/profiling/profile.png`) but still got no idea.

**Comment by CharlesShang** [comment]
BTW, I encountered the same problems  when running other tasks with tf.
This is really weird.

**Comment by xinghedyc** [comment]
@CharlesShang Hi , I move this lines outside the loop: at line 176 in lib/fast_rcnn/train.py
if iter >= cfg.TRAIN.STEPSIZE:
sess.run(tf.assign(lr, cfg.TRAIN.LEARNING_RATE * cfg.TRAIN.GAMMA))
else:
sess.run(tf.assign(lr, cfg.TRAIN.LEARNING_RATE))
And it get faster than before and the problem that the training speed goes down seems to disappear.
You can have a try?

**Comment by CharlesShang** [comment]
definitely
Thank you for your suggestions

**Comment by xinghedyc** [comment]
You're welcome!
Hope to help you!

**Comment by CharlesShang** [comment]
I'm closing this issue. 
If we find out the speed problems still there unsolved, we'll reopen it.
