### ISSUE TITLE
./lib/nms/gpu_nms.so: cannot open shared object file

### ISSUE THREAD

**Issue by mattangus** [CharlesShang/TFFRCNN#40]
I am trying to run the demo. I have succesfully run `make` in the lib folder. I have tried running the demo in the following ways:

`python -m faster_rcnn.demo --model <model>`

`python faster_rcnn/demo.py --model <model>`

I have also tried copying `demo.py` to the root folder and running `python demo.py --model <model>`

All three of these methods of running the demo get the same error:

> Traceback (most recent call last):
>   File "faster_rcnn/demo.py", line 14, in <module>
>     from lib.networks.factory import get_network
>   File "./lib/__init__.py", line 1, in <module>
>     import fast_rcnn
>   File "./lib/fast_rcnn/__init__.py", line 9, in <module>
>     from . import train
>   File "./lib/fast_rcnn/train.py", line 15, in <module>
>     from .nms_wrapper import nms_wrapper
>   File "./lib/fast_rcnn/nms_wrapper.py", line 10, in <module>
>     from ..nms.gpu_nms import gpu_nms
> ImportError: ./lib/nms/gpu_nms.so: cannot open shared object file: No such file or directory

Any ideas how to fix this?

**Comment by hadign20** [comment]
same problem here. Did you find any solution?
