### ISSUE TITLE
ckpt file for demo.py after training

### ISSUE THREAD

**Issue by rgsachin** [CharlesShang/TFFRCNN#47]
After running training, ie
`python ./faster_rcnn/train_net.py --gpu 0 --weights ./data/pretrain_model/VGG_imagenet.npy --imdb voc_2007_trainval --iters 70000 --cfg  ./experiments/cfgs/faster_rcnn_end2end.yml --network VGGnet_train --set EXP_DIR exp_dir`
The last line in log prints 
`
Wrote snapshot to: /xxxx/VGGnet_fast_rcnn_iter_70000.ckpt
done solving
`
But I see three files 
`
VGGnet_fast_rcnn_iter_70000.ckpt.data-00000-of-00001
VGGnet_fast_rcnn_iter_70000.ckpt.index
VGGnet_fast_rcnn_iter_70000.ckpt.meta
`
I then trying to run demo. none of them works with 
`
python ./faster_rcnn/demo.py --model model_path
`
how can i get single ckpt file similar to the one that can downloaded  (https://github.com/CharlesShang/TFFRCNN#download-list) `VGGnet_fast_rcnn_iter_150000.ckpt` as per the instructions in readme ?

**Comment by ChrisDal** [comment]
In fact, the files correspond to : 
- `VGGnet_fast_rcnn_iter_70000.ckpt.data-00000-of-00001` : data itself (weigths and all) 
- `VGGnet_fast_rcnn_iter_70000.ckpt.index` : (I actually have no idea haha) 
- `VGGnet_fast_rcnn_iter_70000.ckpt.meta` : the graph definition and all metadata associated

Tensorflow can restore the model from a trio of `model.ckpt.index` , `model.ckpt.meta,` `model.ckpt.data` with for example here  `args.model = model.ckpt` :

> saver = tf.train.Saver()
    saver.restore(sess, args.model)

But to run the demo from this training, you have to change the condition on the existence of the model which is either on the `model.ckpt` file (that may not exist), either on the `model.ckpt.xxxx` file(s) (where you can't restore the session). Theses lines test if the user gave a `model.ckpt.xxxx` file and then give to the `saver` the right `model.ckpt`.

    if not os.path.splitext(args.model)[1] == 'ckpt':
        model_path = args.model
        args.model = os.path.splitext(args.model)[0] 

       
    if args.model == ' ' or not os.path.exists(model_path):
        print ('current path is ' + os.path.abspath(__file__))
        raise IOError(('Error: Model not found.\n'))


You can add it/replace in the **demo.py** , just after the parsing of the args.  Then give the path to an existing model file e.g : 

`python ./faster_rcnn/demo.py --model dir_model_path/model.ckpt.meta`

A link to an article which explain how the data that is saved [[1](https://blog.metaflow.fr/tensorflow-saving-restoring-and-mixing-multiple-models-c4c94d5d7125)] . That's just a little solution, I  am not a python expert neither a tensorflow expert.

**Comment by rgsachin** [comment]
Thanks @ChrisDal , I believe the trio files format introduced as part of the new saver of Tensorflow - tf.train.SaverDef.V2 which is defaulted now. 
Ideal below is recommended way to read the new saver files, below code in demo.py should fix, but
`
saver = tf.train.import_meta_graph(args.model+'.meta')
saver.restore(sess, args.model)
`
But I ran into some other issues. what seem to solve it forcing the saver to V1 format in train.py
`
self.saver = tf.train.Saver(max_to_keep=100,write_version=tf.train.SaverDef.V1)
`

**Comment by zyclarkcheng** [comment]
thanks @rgsachin. 
hello, did you mean modify self.saver = tf.train.Saver(max_to_keep=100)  in train.py  to  self.saver = tf.train.Saver(max_to_keep=100,write_version=tf.train.SaverDef.V1)  ?
In this way how should I restore the result file?(I am now training the kitti and waiting for the result file )

**Comment by zyclarkcheng** [comment]
Thanks for @CharlesShang your work.
I have trained KITTI dataset and get ckpt.meta, ckpt.index files, and I switch to CLASSES = ('__background__','person','bike','motorbike','car','bus') in demo.py, and import the meta graph
saver = tf.train.import_meta_graph(model) .
BUT I still can not test demo images, so I change self.saver = tf.train.Saver(max_to_keep=100) in train.py to  self.saver = tf.train.Saver(max_to_keep=100,write_version=tf.train.SaverDef.V1)  based on @rgsachin , after training again yielding real ckpt file,  I fail to run demo again...
Could you give me some suggestions ? thanks

**Comment by chrenlily** [comment]
@zyclarkcheng  Did you solve the problem？could you help me ?I got the same problem
