### ISSUE TITLE
What's the difference between your project and Faster-rcnn_TF ?

### ISSUE THREAD

**Issue by miraclebiu** [CharlesShang/TFFRCNN#5]
I have used the Faster-rcnn_TF project for a while  , and I want to know these difference.

**Comment by CharlesShang** [comment]
Thank you noticing my work.
I explained it in README.md. It's just a personal repo. I find the original code base is quite complex, python dependency, many unnecessary transpose, reshape, and some bugs. 
Just did some modifications for my work. 
That's it.
