### ISSUE TITLE
ImportError: No module named lib.networks.factory

### ISSUE THREAD

**Issue by 157995010** [CharlesShang/TFFRCNN#6]
Hi, Charles. When I run your project ` python ./faster_rcnn/demo.py --model vgg_model_path`, I met the error `ImportError: No module named lib.networks.factory`. However, when I open Ipython in the `TFFRCNN` directory and` 
from lib.networks.factory import get_network`, I can import it correctly.
How can I fix this problem, thanks very much~

**Comment by CharlesShang** [comment]
@157995010 
I think you can insert these lines below
`this_dir = osp.dirname(__file__)`
`sys.path.insert(0, this_dir + '/..')`
in demo.py before `import lib.networks.factory`
