### ISSUE TITLE
Does it support multi-gpu training?

### ISSUE THREAD

**Issue by KeyKy** [CharlesShang/TFFRCNN#8]
Does it support multi-gpu training? Thanks!

**Comment by CharlesShang** [comment]
Nope. I dont have multiple gpus..
But Training is quite fast, about 8h for VOC07 (VGG16, titan x, 80k iters).

**Comment by jackytu256** [comment]
Hi @CharlesShang ,
  Thanks for sharing the implementation of FRCNN via tensorflow to us.

I wanna implement multiple gpu version so could you please give some tips how to implement this ?

Thanks

**Comment by CharlesShang** [comment]
Sorry, I havent written anything code for multigpus.
