### ISSUE TITLE
How to implement iter_size like py-faster-rcnn(caffe)  in TFFRCNN? Thanks!

### ISSUE THREAD

**Issue by zxt881108** [CharlesShang/TFFRCNN#9]
I think iter_size is so important to improve the mAP when training a RPN detection model with IMS_PER_BATCH=1. In py-faster-rcnn. we can set iter_size=N(N=2,4,8...) to increase the image diversity.

**Comment by CharlesShang** [comment]
Hi, @zxt881108 would you like to post the mAP with `IMS_PER_BATCH=2` or `IMS_PER_BATCH=4` ? 
I do think diversity matters, but to what degree? 
Now the mAP I got after 80k iters is 0.70 (with VGG16, 07 trainval, IMS_PER_BATCH=1), same with the original paper.
